---
title: "Entregable final: Informe de an치lisis de datos"
---

Esta actividad es **obligatoria para los estudiantes que cursan en modalidad seminario** (si sos estudiante de plenario te lo ofrecemos como un recurso m치s para practicar).

La propuesta consiste en realizar una secuencia de an치lisis de datos a partir de una de las bases disponibles en [cuanti.psico.edu.uy/panel](http://cuanti.psico.edu.uy/panel) (en particular ENDIS, ARISTAS, SERCE o Triada Oscura).

La idea es que este trabajo te ayude a desarrollar cierta autonom칤a en el planteo de preguntas de investigaci칩n, a darte cuenta qu칠 an치lisis son adecuados seg칰n las variables disponibles y la pregunta que pretendes responder y, por 칰ltimo, que puedas ensayar la comunicaci칩n escrita de estos resultados.

Este trabajo se va a desarrollar paso a paso a lo largo del semestre seg칰n avanzamos en las distintas unidades tem치ticas, hasta realizar la entrega final (a coordinar con tu docente referente de seminario).

Para realizar el trabajo debes descargar el modelo de reporte en Word, que ya contiene las secciones y formato esperado del entregable.

<a href="descargabes/entregable.docx" download>
  游닌 Descargar Word
</a>