---
title: "Práctico: Describir los datos"
---

## Contenidos

-   Inspección visual de una base de datos.

-   Identificar variables y su tratamiento.

-   Visualización de datos: histograma

-   Visualización de datos: boxplot

-   Medidas de tendencia central

-   Medidas de dispersión

## Panel de datos\| Primeros pasos: conocer (y amigarme con) los datos

Accede a cuanti.psico.edu.uy/panel Localiza la base de datos \_\_\_\_\_\_\_\_\_\_ Vamos a explorarla.

### Contextualizar los datos

Antes de empezar a trabajar con los datos necesitamos un poco de contexto. Accede a la información sobre la base \_\_\_\_\_\_\_\_\_. Activa el botón “Acerca de la base” para conocer de qué se trata.

### ¿Qué variables contiene la base? ¿Qué tipo de variables son (o cómo fueron tratadas)?

-   Lee el apartado Escalas de medición del libro

-   Activa el botón Mostrar resumen. Identifica variables y niveles de la variable.

-   Observa la base de datos. ¿Cuántas variables contiene?

-   Observa el diccionario de variables ¿Qué se evalúa? ¿Cómo lo evaluaron?

-   Identifica cómo ha sido tratada cada variable e intenta clasificarla

-   Registra tu clasificación. Compara tu registro en el subgrupo

-   Lee el apartado El rol de las variables: predictoras y dependientes del libro

-   Algún ejercicio cruzando variables de panel para que tengan que pensar en variable independiente y dependiente (el libro propone variable manipulada (predictora) y variable medida (resultado) como una nomenclatura más intuitiva)

### ¡Miremos los datos!

Lee el capítulo 2. Describir los datos Selecciona la base de datos\_\_\_\_\_\_\_\_\_\_\_

<details>

<summary><strong>¿Necesitas ayuda?</strong></summary>

Elegir análisis \> Ver datos

Mmm… mejor examinemos los datos en un formato visual. Como vimos en el libro, vamos a convertir esos números a otras formas de visualización de datos.

</details>

El primer resumen oficial: realiza un histograma de la variable \_\_\_\_\_\_\_\_\_\_\_\_\_.

<details>

<summary><strong>¿Necesitas ayuda?</strong></summary>

Elegir análisis \> Histograma\> Elegir variable 1 (numérica)

</details>

Cambia el ancho de los intervalos (bins) y observa cómo cambia el gráfico. ¿Qué ancho de bin seleccionarías finalmente? Repite el procedimiento para otras variables ¿Cómo es la forma del histograma en cada variable? (ej. simetría, “picos”) Ahora explora la opción gráfica Boxplot

### De muchos números a uno: tendencia central y dispersión

En el libro y en el ejercicio anterior vimos que podemos hacernos una idea de los datos al representarlos mediante gráficos. Ahora vamos a examinar la tendencia central y la dispersión de los datos a través de números.

-   Obtiene la tabla de estadísticos descriptivos

-   ¿Por qué para algunas variables no se ofrece el valor de la media y otros estadísticos?

-   ¿Qué estadísticos expresan la tendencia central en los datos? ¿Cuál es la dispersión de los datos?

-   Localiza los valores de tendencia central y dispersión para una variable

-   Recupera el histograma del ejercicio anterior para esa variable. Si dibujaras líneas verticales para marcar la Media, Moda y Mediana. ¿Coinciden los tres valores? ¿Cuál es más sensible a los valores extremos?
